### ISSUE TITLE
Please wait for autoanalysis finish first!, Aborted

### ISSUE THREAD

**Issue by dadapa5** [kweatherman/yara4ida#3]
The automatic analysis has been completed, but the plugin cannot run

**Comment by kweatherman** [comment]
Lets troubleshoot:
So you get this message "autoanalysis finish first!, Aborted"?
I think there is an issue where there is another reason to abort, but it just falls through to that message.
IDB is an x86 or AMD64 platform?

What version of IDA? Should be good from IDA version 7 to 8'ish.

**Comment by kweatherman** [comment]
Closed due to inactivity. OP never got back to troubleshoot.
No one else reported this issue.
